version: '3.8'
name: delivery

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '1000:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '1001:5672'
      - '1002:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data

  redis:
    image: redis:alpine
    ports:
      - '2000:6379'
    volumes:
      - users_redis_data:/var/lib/redis/data

volumes:
  postgres_data:
  rabbitmq_data:
  users_redis_data:
