name: Determine Affected Apps

on:
  workflow_call:
    outputs:
      affected_nestjs:
        description: 'Affected NestJS apps'
        value: ${{ jobs.determine-affected.outputs.affected_nestjs }}
      affected_react:
        description: 'Affected react apps'
        value: ${{ jobs.determine-affected.outputs.affected_react }}

jobs:
  determine-affected:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - id: set-affected
        run: |
          affected=$(npx nx print-affected --select=projects)
          affected_nestjs=$(echo "$affected" | grep -E 'api-' | tr '\n' ',' | sed 's/,$//')
          affected_react=$(echo "$affected" | grep -E 'app-|web-' | tr '\n' ',' | sed 's/,$//')
          echo "::set-output name=affected_nestjs::$affected_nestjs"
          echo "::set-output name=affected_react::$affected_react"
        env:
          NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    outputs:
      affected_nestjs: ${{ steps.set-affected.outputs.affected_nestjs }}
      affected_react: ${{ steps.set-affected.outputs.affected_react }}
