name: Deploy to Vercel

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      VERCEL_TOKEN:
        required: true
      VERCEL_ORG_ID:
        required: true
      VERCEL_PROJECT_ID:
        required: true

jobs:
  deploy-to-vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm i -g vercel
      - name: Deploy affected React apps to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          IFS=',' read -ra AFFECTED_APPS <<< "${{ needs.determine-affected.outputs.affected_react }}"
          for app in "${AFFECTED_APPS[@]}"; do
            echo "Deploying $app to Vercel ${{ inputs.environment }}"
            if [[ "${{ inputs.environment }}" == "PRODUCTION" ]]; then
              vercel --token $VERCEL_TOKEN --scope $VERCEL_ORG_ID --prod deploy apps/$app
            else
              vercel --token $VERCEL_TOKEN --scope $VERCEL_ORG_ID deploy apps/$app --env NEXT_PUBLIC_ENV=${{ inputs.environment }}
            fi
          done
