name: Production CD

on:
  pull_request:
    branches: [main]
  pull_request_target:
    types: [closed]
    branches: [main]

concurrency:
  group: production-deploy
  cancel-in-progress: true

jobs:
  determine-affected:
    if: github.event.pull_request.merged == true
    uses: ./.github/jobs/determine-affected.yml

  prisma-migrate:
    needs: determine-affected
    uses: ./.github/jobs/prisma-migrate.yml
    with:
      environment: PRODUCTION

  deploy-to-railway:
    needs: prisma-migrate
    uses: ./.github/workflows/railway-deploy.yml
    with:
      environment: PRODUCTION
    secrets:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  deploy-to-vercel:
    needs: deploy-to-railway
    uses: ./.github/workflows/vercel-deploy.yml
    with:
      environment: PRODUCTION
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
